### ISSUE TITLE
Exception within exception when not using form-submit

### ISSUE THREAD

**Issue by danieldotnl** [danieldotnl/ha-multiscrape#36]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/rest/entity.py", line 73, in _handle_coordinator_update
    self._update_from_rest_data()
  File "/config/custom_components/multiscrape/sensor.py", line 154, in _update_from_rest_data
    value = self._scrape(
  File "/config/custom_components/multiscrape/entity.py", line 75, in _scrape
    self.rest.notify_scrape_exception()
  File "/config/custom_components/multiscrape/data.py", line 66, in notify_scrape_exception
    if self._form_resubmit_error:
AttributeError: 'ScrapedRestData' object has no attribute '_form_resubmit_error'

**Comment by gabrielmc9** [comment]
I have the same issue.  The sensor is successfully populated with data once, upon reboot, then I get the above error once every scan_interval.  The sensor data remains "stale" since the last reboot.

**Comment by danieldotnl** [comment]
I didn't even notice but you are right that the data doesn't get updated anymore. 
Did it for you also start after upgrading to 2021.7? 

And what is the original exception for you?

**Comment by gabrielmc9** [comment]
Versions:
  HA: 2021.6.6
  Multiscrape: 5.0.0
  HACS: 1.13.2

I just rebooted again.  Successful initial update but no log entry since no errors generated.  First error logged, scan_interval seconds after initial load:

2021-07-08 10:17:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/multiscrape/entity.py", line 67, in _scrape
tag = content.select(select)[index]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/components/rest/entity.py", line 73, in _handle_coordinator_update
self._update_from_rest_data()
File "/config/custom_components/multiscrape/sensor.py", line 154, in _update_from_rest_data
value = self._scrape(
File "/config/custom_components/multiscrape/entity.py", line 75, in _scrape
self.rest.notify_scrape_exception()
File "/config/custom_components/multiscrape/data.py", line 66, in notify_scrape_exception
if self._form_resubmit_error:
AttributeError: 'ScrapedRestData' object has no attribute '_form_resubmit_error'

**Comment by danieldotnl** [comment]
07ffe3c91292be6a524752bbbb9d64ec2613a0fc

**Comment by gabrielmc9** [comment]
Hi @danieldotnl - The problem is indeed fixed.  Many thanks.  The "stale" data refers to sensor data not updating & retaining old values when the code failed.
